[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
opacity = 0.8
blur = true
padding = { x = 15, y = 15}

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
size = 13 
